[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PUBLIC_SITE_ENV = "production"

[context.stage]
  command = "npm run build"
[context.stage.environment]
  PUBLIC_SITE_ENV = "staging"

[context.branch-deploy]
  command = "npm run build"
[context.branch-deploy.environment]
  PUBLIC_SITE_ENV = "staging"

[context.deploy-preview]
  command = "npm run build"
[context.deploy-preview.environment]
  PUBLIC_SITE_ENV = "staging"

[functions]
  directory = "netlify/functions"
